config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/home", to: "static_pages#home"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  post "/signup", to: "user#create"
  get "sessions/new"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts do
    resources :comments
  end

  resources :users, only: [:show, :new, :create]
  resources :posts, only: [:new, :create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  default_scope -> {order(created_at: :asc)}
  validates :content, presence: true, length: {maximum: Settings.micropost.max_length_body}
  scope :feed_load_comment, ->id{where "user_id = ?", id}
  scope :sort_by_created_at, ->{order created_at: :desc}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :comment_params, only: [:new, :create, :update]
  before_action :find_post
  before_action :find_comment, only: [:create, :destroy]
  def create
      @comment = @post.comments.create comment_params
      @comment.user_id = current_user.id
      if @comment.save
        flash[:success] = t ".success_create_comment"
        respond_to do |format|
          format.html {redirect_to @post}
          format.js
        end
      else
        flash[:danger] = "Can't insert blank"
        respond_to do |format|
        format.html {redirect_to @post}
        format.js
        end
      end
  end

  def destroy
    if @comment.destroy
      respond_to do |format|
          format.html {redirect_to @post}
          format.js
      end
    else
      respond_to do |format|
        format.html {redirect_to @post}
        format.js
      end
    end
  end

  def load_more

  end
  private

  def comment_params
    params.require(:comment).permit :content
  end

  def find_post
    @post = Post.find params[:post_id]
  end

  def find_comment
    @comment = @post.comments.find_by id: params[:id]
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comments-list">
  <div class="media <%= comment.id %>">
    <p class="pull-right"><small><%= time_ago_in_words comment.created_at %></small></p>
        <%= link_to gravatar_for(comment.user, size: 50), comment.user, class: "media-left" %>
      <div class="media-body">
        <h4 class="media-heading user_name"><%= comment.post.user.name %></h4>
          <%= comment.content %>
          <% if current_user.is_current_user? comment.user %>
            <p><small> <%= link_to post_comment_path(comment.post, comment.id),
            method: :delete, data: {confirm: t(".you_sure")}, remote: true do %>
            Delete
            <% end %>
            </small></p>
          <% end %>
      </div>
  </div>
</div>

app/views/comments/_comment_form.html.erb
    <%= form_for ([@post, @post.comments.build], remote: true) do |f| %>
      <%= f.text_field :content, class: "form-control" %>
      <%= f.submit t(".submit"), class: "btn btn-primary send" %>
    <% end %>

app/views/comments/create.js.erb
$('#comments').append("<%= j render @comment %>");
$('#comment_content').val("");
$('#comment_content').focus();
$('.unit-100 a').html("<%= @comment.post.comments.count %>")
toastr.success('Delete success');

app/views/comments/destroy.js.erb
$('.media.<%= @comment.id %>').fadeOut(function() {
  $(this).remove();
});
$('.unit-100 a').html("<%= @comment.post.comments.count %>")
$('#comment_content').val("");
$('#comment_content').focus();