config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/home", to: "static_pages#home"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  post "/signup", to: "user#create"
  get "sessions/new"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts do
    resources :comments
  end

  resources :users, only: [:show, :new, :create]
  resources :posts, only: [:new, :create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".the" %> <%= link_to t(".rails"), "http://www.railstutorial.org/" %>
    <%= t ".by" %> <%= link_to t(".mychael"), "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".news"), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".sample"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".users"), users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <%= link_to current_user.name, "#", class: "dropdown-toggle", title:"",
              data: {toggle: "dropdown"} %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".setting"), users_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim"%>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div id="toast-container" class="toast-top-right" aria-live="polite" role="alert">
        <%= content_tag :div, content_tag(:div, message,class: "toast-message"), class: "toast toast-#{message_type}", style: "display:block;" %>
      </div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug params if Rails.env.development? %>
    </div>
  </body>
</html>